### ISSUE TITLE
Err: undefinde method 'apply' for IssuePatch:Module

### ISSUE THREAD

**Issue by projectplant** [jkraemer/redmine_percent_done#1]
Hi,

I've a problem in installing this plugin with 

``` ruby
rake aborted!
NoMethodError: undefined method `apply' for IssuePatch:Module
/opt/redmine/current/plugins/redmine_percent_done/lib/redmine_percent_done.rb:3:in `setup'
/opt/redmine/current/plugins/redmine_percent_done/init.rb:20:in `block in <top (required)>'
```

My environment:

``` html
Environment:
  Redmine version                3.1.1.stable.14752
  Ruby version                   2.2.0-p0 (2014-12-25) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Git                            1.9.1
  Filesystem                     
  Xitolite                       1.9.1
Redmine plugins:
  advanced_roadmap_v2            2.4.2
  clipboard_image_paste          1.10
  event_notifications            3.0.0
  manage_wiki_view_page_permission 0.0.1
  planner                        0.5
  plantuml                       0.3.0
  recurring_tasks                2.0.0-pre
  redcase                        1.0
  redmine_agile                  1.3.11
  redmine_archive_issue_categories 0.3.0
  redmine_banner                 0.1.1
  redmine_bootstrap_kit          0.2-devel
  redmine_checklists             3.1.3
  redmine_code_review            0.7.0
  redmine_contacts               4.0.2
  redmine_create_git             0.1.0
  redmine_default_custom_query   1.1.2
  redmine_dmsf                   1.5.5
  redmine_documents              1.0.0
  redmine_email_fetcher          0.3.1
  redmine_email_images           0.1.1
  redmine_git_hosting            1.1.3
  redmine_group_owners           2.0.0
  redmine_hide_estimated_hours   1.0.8
  redmine_incoming_emails        0.0.1
  redmine_issue_completion       0.0.2
  redmine_issue_icons            1.0.0
  redmine_issue_tabs             1.1.1
  redmine_issues_tree            0.0.5
  redmine_journal_folder         0.0.2
  redmine_jstoolbar_ext          0.2.1
  redmine_jstoolbar_ext_buttons  0.2.0
  redmine_jstoolbar_ext_coderay  0.2.0
  redmine_jstoolbar_ext_images   0.2.0
  redmine_lightbox2              0.2.2
  redmine_login_audit            0.2.0
  redmine_mail_reminder          3.0.0.0001
  redmine_planning               1.0.0
  redmine_print_issue            1.0.3
  redmine_query_share            1.0.3
  redmine_scm                    0.5.1
  redmine_show_assigned_to_activity 0.0.1
  redmine_silencer               0.4.0
  redmine_spent_time             3.1.2
  redmine_tweaks                 0.5.5
  redmine_version_email          3.0.0
  redmine_vote                   1.2.2
  redmine_wiki_extensions        0.7.0
  redmine_wiki_lists             0.0.5
  redmine_wktime                 2.0
  redmine_workflow_enhancements  0.4.0
  redmine_xls_export             0.2.1.t9
  redmine_xlsx_format_issue_exporter 0.1.2
  redrisk                        1.0.1
  simple_author_change           0.1.1
  unread_issues                  1.5.0
  wiking                         1.0.0b
```

Thanks.
Marc

**Comment by jkraemer** [comment]
Hi,

This is certainly not a problem of this plugin as `RedminePercentDone::IssuePatch` has this method.

Please check your other plugins, I bet one of them misbehaves by declaring an `IssuePatch` module in the top level namespace (look for lib/issue_patch.rb). Fun fact - check the [blog post](https://jkraemer.net/2015/11/how-to-create-a-redmine-plugin) describing the creation of this plugin along with a set of best practices - it mentions exactly this problem as the reason for namespacing any Redmine plugin's code.

Please file a bug with the other plugin once you found it. As a quick work around you may change the reference to `IssuePatch` to `::RedminePercentDone::IssuePatch`, but like I said, the bug is where ::IssuePatch is declared.

**Comment by projectplant** [comment]
Hi,

Thanks for your help, it looks like, that the Redcase-Plugin causes the problem. I've not idea how to fix it there ... and they are not very active in supporting issues. Nevermind, thanks for your help.
